[project]
name = "qubra_bench"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "Bla bla bla"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/KIT-TVA/qubra-bench"
"Bug Tracker" = "https://github.com/KIT-TVA/qubra-bench/issues"

[tool.pytest.ini_options]
markers = [
    "kit: test KIT implementations (in case of parallel implementations)",
    "rub: test RUB implementations (in case of parallel implementations)",
]
